"use client";

import { useEffect, useState } from "react";

const A = "/portfolio/";
const asset = (src: string) => `${A}${src}?v=20260918-complete`;
type Detail = { src: string; title: string; eyebrow: string; text: string };

const plans: Detail[] = [
  { src: "level-01-natural-v5.jpg", title: "Level 01 · Ground floor", eyebrow: "Measured plan 01", text: "The ground floor records the compressed entrance sequence, living spaces, and relationship to the garden. It shows how movement is redirected before the house gradually opens." },
  { src: "img-001.jpg", title: "Level 02 · Private rooms", eyebrow: "Measured plan 02", text: "The upper level gathers the private rooms around controlled openings and changing wall heights, continuing the house’s balance between connection and privacy." },
  { src: "img-002.jpg", title: "Level 03 · Roof terrace", eyebrow: "Measured plan 03", text: "Tall walls transform the roof into an inward-looking outdoor room. The plan traces enclosure, selective views, and the framing of sky." },
];

const roomDetails: Detail[] = [
  { src: "img-003.jpg", title: "Popped-out room study 01", eyebrow: "Oblique detail", text: "This extracted room isolates one spatial moment from the larger oblique. Drawing it separately made the relationship between enclosure, opening, and circulation easier to study." },
  { src: "img-004.jpg", title: "Popped-out room study 02", eyebrow: "Oblique detail", text: "A second extracted room examines depth and connection at a closer scale, translating a small but important part of the full building into a focused spatial study." },
];

function Frame({ src, alt, className = "", contain = false }: { src: string; alt: string; className?: string; contain?: boolean }) {
  return <figure className={`frame ${contain ? "contain" : ""} ${className}`}><img src={asset(src)} alt={alt} loading="lazy" /></figure>;
}

function Modal({ detail, close }: { detail: Detail | null; close: () => void }) {
  useEffect(() => {
    if (!detail) return;
    const escape = (event: KeyboardEvent) => event.key === "Escape" && close();
    document.addEventListener("keydown", escape); document.body.classList.add("modalOpen");
    return () => { document.removeEventListener("keydown", escape); document.body.classList.remove("modalOpen"); };
  }, [detail, close]);
  if (!detail) return null;
  return <div className="modal" role="dialog" aria-modal="true" aria-label={detail.title} onMouseDown={(e) => e.target === e.currentTarget && close()}>
    <div className="modalPanel"><button className="modalClose" onClick={close}>Close ×</button><div className="modalImage"><img src={asset(detail.src)} alt={detail.title} draggable="false" /></div><div className="modalCopy"><p className="eyebrow">{detail.eyebrow}</p><h2>{detail.title}</h2><p>{detail.text}</p><p className="protectedNote">Portfolio view · © 2026 Amanda Masi</p></div></div>
  </div>;
}

export default function App() {
  const [detail, setDetail] = useState<Detail | null>(null);
  const [emailCopied, setEmailCopied] = useState(false);
  const copyEmail = async () => {
    try {
      await navigator.clipboard.writeText("amandau.masi@gmail.com");
      setEmailCopied(true);
      window.setTimeout(() => setEmailCopied(false), 2400);
    } catch {
      window.location.href = "mailto:amandau.masi@gmail.com?subject=Architecture%20Portfolio%20Inquiry";
    }
  };
  return <main id="top">
    <header className="topNav"><a className="monogram" href="#top">AM</a><div><a href="#contact" aria-label="Go to Amanda Masi contact information">Contact</a><a className="navCta" href="/Amanda_Masi_Portfolio.pdf" target="_blank" rel="noreferrer">PDF Portfolio ↗</a></div></header>
    <nav className="portfolioKey" aria-label="Portfolio sections"><p>Portfolio index</p><a href="#profile"><span>00</span>Overview</a><a href="#casa"><span>01</span>Casa Barragán</a><a href="#cube"><span>02</span>Cube Study</a><a href="#studies"><span>03</span>Drawings</a><a href="#experience"><span>04</span>Experience</a></nav>

    <section className="hero page" id="profile"><div className="heroCopy"><p className="eyebrow">Architecture · Materials · Human experience</p><h1>Amanda<br />Masi</h1><p className="dek">Architecture student exploring how light, sequence, material, and human experience shape space.</p><a className="button" href="#casa">View selected work ↓</a></div><Frame src="cube-landscape-vivid.jpg" alt="Physical architecture model set into a terraced landscape" className="heroImage vividModel" /><div className="profile"><p className="eyebrow">Profile</p><h2>Design grounded in experience.</h2><p>Architecture student at Portland State University pursuing a B.S. in Architecture with a minor in Sustainable Urban Development. My work spans spatial analysis, model making, hand drafting, visual communication, and material research.</p></div></section>

    <section className="page project" id="casa"><header className="projectHead"><div><p className="sectionNo">01 / Precedent + spatial analysis</p><h1>Casa Luis<br />Barragán</h1></div><div><p className="lead">A measured drawing and model study of light, mass, privacy, and the gradual reveal of space.</p><p className="meta">Visual Communication 2 · PSU · Spring 2026 · Individual academic work</p></div></header><div className="casaIntro"><p className="eyebrow">Precedent / 1948</p><h2>A house, studio, and carefully choreographed sequence.</h2><p>Casa Estudio Luis Barragán in Tacubaya, Mexico City, was designed by Mexican architect Luis Barragán and completed in 1948. Its quiet street exterior gives way to vivid color, indirect light, thick walls, gardens, and deliberate moments of reveal and conceal. It became a UNESCO World Heritage Site in 2004.</p></div><aside className="authorshipNote" aria-label="Casa Barragán project authorship"><strong>Authorship note</strong><span>Academic precedent study of Casa Estudio Luis Barragán. Original building by Luis Barragán; measured drawings, physical model, photographs, and written analysis presented here are by Amanda Masi.</span></aside>
      <div className="imageMap modelExplorer"><img src={asset("casa-model-vivid.jpg")} alt="Casa Luis Barragán physical model" /><div className="modelPrompt"><b>Explore the model</b><small>Tap the magnifying glasses on the building to open each plan.</small></div><button className="mapHotspot modelLevel level1" aria-label="Magnify ground floor plan" onClick={() => setDetail(plans[0])}><span className="lens" aria-hidden="true">⌕</span><span className="levelNo">01</span></button><button className="mapHotspot modelLevel level2" aria-label="Magnify private level plan" onClick={() => setDetail(plans[1])}><span className="lens" aria-hidden="true">⌕</span><span className="levelNo">02</span></button><button className="mapHotspot modelLevel level3" aria-label="Magnify roof terrace plan" onClick={() => setDetail(plans[2])}><span className="lens" aria-hidden="true">⌕</span><span className="levelNo">03</span></button></div>
      <div className="concept"><div><p className="eyebrow">Central idea</p><h2>Reveal and conceal</h2></div><p>Changing wall heights, filtered light, and carefully placed openings choreograph movement and discovery. Drawing and making exposed spatial relationships that were difficult to understand in plan alone.</p></div>
      <div className="planCards">{plans.map((plan) => <button key={plan.title} onClick={() => setDetail(plan)}><img src={asset(plan.src)} alt="" /><span><b>{plan.title}</b><small>Open measured plan ↗</small></span></button>)}</div>
      <article className="obliqueFeature"><div className="featureTitle"><p className="eyebrow">Featured drawing</p><h2>Complete plan oblique</h2><p>This intricate drawing brings the building’s rooms, walls, and vertical relationships into one coordinated view. Tap either magnifying glass directly on the two popped-out rooms to inspect that part of the drawing.</p></div><div className="imageMap obliqueMap"><img src={asset("img-005.jpg")} alt="Complete plan oblique drawing of Casa Luis Barragán" /><button className="mapHotspot obliqueSpot obliqueTop" aria-label="Magnify upper popped-out room" onClick={() => setDetail({ src: "oblique-room-top-detail.jpg", title: "Upper popped-out room", eyebrow: "Plan oblique / Focus detail 01", text: "This extracted stair and room sequence isolates a compact spatial connection from the complete oblique. The close-up makes the careful alignment, stair geometry, openings, and changes in enclosure easier to read." })}><span className="lens" aria-hidden="true">⌕</span></button><button className="mapHotspot obliqueSpot obliqueMiddle" aria-label="Magnify lower popped-out room" onClick={() => setDetail({ src: "oblique-room-middle-detail.jpg", title: "Lower popped-out room", eyebrow: "Plan oblique / Focus detail 02", text: "This second extracted space shows another stair and room relationship at a larger scale. Its overlapping construction lines reveal the precision required to keep the projection aligned with the complete building drawing." })}><span className="lens" aria-hidden="true">⌕</span></button><span className="mapHint">Tap a magnifying glass to inspect a room</span></div></article>
      <section className="perspectiveFeature"><header><p className="eyebrow">Spatial translation</p><h2>One-point perspective studies</h2><p>Two interior views carry the measured analysis into an experiential scale, showing how walls, openings, and changes in depth would be perceived from within the house.</p></header><div className="perspectiveGrid"><button onClick={() => setDetail({ src: "img-003.jpg", title: "One-point perspective 01", eyebrow: "Casa Luis Barragán / Interior study", text: "This perspective studies the sequence of enclosure and opening from a single viewpoint. The converging construction lines organize depth while the restrained linework keeps attention on the room’s proportions." })}><img src={asset("img-003.jpg")} alt="First one-point perspective study of Casa Luis Barragán" /><span>Perspective 01 <small>Click to enlarge ↗</small></span></button><button onClick={() => setDetail({ src: "img-004.jpg", title: "One-point perspective 02", eyebrow: "Casa Luis Barragán / Interior study", text: "The second perspective focuses on another spatial threshold, using alignment and scale to make the relationship between adjacent planes and openings legible." })}><img src={asset("img-004.jpg")} alt="Second one-point perspective study of Casa Luis Barragán" /><span>Perspective 02 <small>Click to enlarge ↗</small></span></button></div></section>
      <section className="modelEvidence"><header><p className="eyebrow">Why these views matter</p><h2>Testing the drawing in three dimensions</h2><p>The final model photographs verify ideas first studied through plans, obliques, and perspectives. Together, they show how the separate drawings translate into one spatial sequence.</p></header><div className="photoStrip"><article><Frame src="img-007.jpg" alt="Casa Barragán model viewed from above" /><div><span>01 / Overhead organization</span><p>The overhead view makes the relationships between rooms, circulation, openings, and enclosed outdoor space legible as one composition.</p></div></article><article><Frame src="casa-rear-courtyard.jpg" alt="Rear courtyard view of the Casa Barragán model" /><div><span>02 / Rear courtyard sequence</span><p>This view studies how courtyard edges and changing wall heights shape privacy, frame views, and continue the project’s theme of reveal and conceal.</p></div></article></div></section>
    </section>

    <section className="page project cube" id="cube"><header className="projectHead"><div><p className="sectionNo">02 / Iterative design + model making</p><h1>The Evolution<br />of a Cube</h1></div><p className="lead">A geometric study developed into an occupied landscape through iterative drawing, physical modeling, light, and material.</p></header><div className="cubePrologue"><Frame src="cube-presentation.jpg" alt="Complete cube project presentation" className="wide" contain /><div><span>Process map</span><p>The final review assembled every stage on one wall. Below, the project is unpacked in the order it developed—from a simple geometric operation into an atmospheric place.</p></div></div><div className="cubeSequence">
      <article className="cubeStep stepOne"><div className="stepCopy"><span>01</span><p className="eyebrow">Generate a formal language</p><h2>Begin with a cube</h2><p>Two axonometric transformations tested how a familiar solid could be cut, shifted, and reassembled. The repeated edges established a geometric vocabulary before function or site entered the project.</p></div><div className="stepImages twin"><Frame src="img-009.jpg" alt="First transformed cube axonometric drawing" contain /><Frame src="img-010.jpg" alt="Second transformed cube axonometric drawing" contain /></div></article>
      <article className="cubeStep stepTwo"><div className="stepCopy"><span>02</span><p className="eyebrow">Imagine occupation</p><h2>Turn form into space</h2><p>Loose sketches and one-point perspectives moved the exercise from object to experience. Openings, scale figures, thresholds, and an internal path began to suggest how someone might enter and inhabit the form.</p></div><div className="stepImages storyboard"><Frame src="cube-brainstorm.jpg" alt="Brainstorming and transformation sketches for the cube" contain /><Frame src="img-012.jpg" alt="One-point perspective drawing inside the transformed cube" contain /><Frame src="img-013.jpg" alt="Rendered graphite perspective of the cube interior" contain /></div></article>
      <article className="cubeStep stepThree"><div className="stepCopy"><span>03</span><p className="eyebrow">Build the landscape</p><h2>Give the object a ground</h2><p>The site drawing introduced topography, water, vegetation, and a long diagonal approach. Instead of sitting on a flat base, the cube became one moment in a larger procession through layered terrain.</p></div><div className="sitePair"><Frame src="img-011.jpg" alt="Graphite site plan developing landscape around the cube" contain /><Frame src="cube-stair-detail.jpg" alt="Physical study of the terraced stair and landscape" /></div></article>
      <article className="cubeStep stepFour"><div className="stepCopy"><span>04</span><p className="eyebrow">Material + atmosphere</p><h2>Use texture, light, and scale</h2><p>Corrugated contours create a tactile ground while basswood paths bridge changes in elevation. Blue acrylic suggests water, miniature figures establish scale, and controlled light turns the interior into a distinct atmospheric pause.</p></div><div className="finalSequence"><Frame src="img-014.jpg" alt="Approach through the completed cube landscape" className="vividModel" /><Frame src="cube-landscape-vivid.jpg" alt="Terraced landscape and bridge of the final cube model in vivid balanced light" className="vividModel" /><Frame src="cube-interior-vivid.jpg" alt="Blue-lit interior atmosphere in the final cube model with enhanced shadow detail" className="vividModel" /></div></article>
      <div className="cubeFinal"><p className="eyebrow">Final reading</p><blockquote>What began as a formal transformation became a sequence of approach, threshold, enclosure, light, and release.</blockquote></div>
    </div></section>

    <section className="page project" id="studies"><header className="projectHead"><div><p className="sectionNo">03 / Visual communication</p><h1>Drawing<br />spatial ideas</h1></div><p className="lead">Observation, projection, atmosphere, and depth explored through graphite, collage, charcoal, and hand drafting.</p></header><div className="study"><Frame src="img-017.jpg" alt="Architectural collage and charcoal composition" contain /><div><p className="eyebrow">Atmosphere</p><h2>Collage + charcoal</h2><p>Fragments become one architectural atmosphere through perspective, layering, light, and shadow.</p></div></div><div className="windowFeature"><div className="imageMap windowMap"><img src={asset("img-018.jpg")} alt="Three window drawings studying foreground, middle ground, and background" /><button className="mapHotspot windowSpot bagSpot" aria-label="Magnify the shaded bag and metal heater" onClick={() => setDetail({ src: "window-bag-heater-detail.jpg", title: "Bag + metal heater textures", eyebrow: "Foreground detail / Window study", text: "Layered graphite shading gives the soft bag a folded, fabric-like surface, while repeated curved lines define the rigid metal heater. The contrast between soft and hard textures strengthens the foreground and makes the space feel tactile." })}><span className="lens" aria-hidden="true">⌕</span></button><button className="mapHotspot windowSpot leavesSpot" aria-label="Magnify the negative-space leaves" onClick={() => setDetail({ src: "window-leaves-detail.jpg", title: "Leaves drawn through negative space", eyebrow: "Background detail / Third window", text: "In the third window, the dark background is built around the leaves and branches rather than shading the objects themselves. This negative-space technique lets the pale plant forms emerge from the surrounding value." })}><span className="lens" aria-hidden="true">⌕</span></button><span className="mapHint">Tap the magnifying glasses for drawing details</span></div><div className="windowIntro"><p className="eyebrow">Spatial depth</p><h2>Window study</h2><p>Line weight, value, overlap, and detail distinguish foreground, middle ground, and background. The interactive details focus on contrasting textures in the foreground and negative-space drawing in the third window.</p></div></div><div className="study"><Frame src="img-019.jpg" alt="Lamp and musical instrument orthographic drawing" contain /><div><p className="eyebrow">Projection + alignment</p><h2>Lamp orthographic study</h2><p>Coordinated plans, elevations, and perspectives translate three-dimensional objects through two-dimensional conventions.</p></div></div></section>

    <section className="page project experience" id="experience"><header className="experienceHead"><p className="sectionNo">04 / Professional experience</p><h1>Materials<br />in practice</h1><p className="lead">Daily library work connects material knowledge with clear systems, vendor relationships, and responsible resource management.</p></header><div className="experienceStatement"><h2>Materials Library Assistant<br /><span>Vida Design</span></h2><p>I maintain an accessible working materials library for designers and vendor representatives—creating reference lists, organizing samples, supporting wayfinding, and managing displays that improve product visibility and everyday navigation.</p></div><div className="experienceGrid"><Frame src="vida-brands.jpg" alt="Alphabetical brand reference list" contain /><Frame src="vida-wallcoverings.jpg" alt="Wallcovering category reference" contain /><Frame src="vida-drawers.jpg" alt="Organized sample drawers" /><Frame src="vida-display.jpg" alt="Vendor product display tray" /></div><div className="stewardship"><Frame src="vida-reduction.jpg" alt="Amanda and coworker sorting materials for reuse" /><div><p className="eyebrow">Stewardship</p><h2>Reducing material waste</h2><p>Unused samples were sorted by brand for return, recycling, and donation. Discarding was treated as a last resort.</p></div></div></section>

    <footer id="contact"><div><p className="eyebrow">Seeking a part-time architecture internship</p><h2>Let’s build something thoughtful together.</h2><p className="contactNote">Compose an email in your browser, copy my address, or call directly.</p></div><div className="contactActions"><a className="contactPrimary" href="https://mail.google.com/mail/?view=cm&fs=1&to=amandau.masi%40gmail.com&su=Architecture%20Portfolio%20Inquiry" target="_blank" rel="noreferrer" aria-label="Compose an email to Amanda Masi in Gmail">Email Amanda in browser ↗</a><button type="button" onClick={copyEmail} aria-live="polite">{emailCopied ? "Email copied ✓" : "Copy email address"}</button><a href="tel:+18087470344" aria-label="Call Amanda Masi at 808 747 0344">Call · 808-747-0344</a><a href="https://www.linkedin.com/in/amanda-m-b479bb216" target="_blank" rel="noreferrer">LinkedIn ↗</a><small>amandau.masi@gmail.com</small></div><div className="copyright"><strong>© 2026 Amanda Masi. All rights reserved.</strong><span>Unless otherwise credited, all drawings, models, photographs, and written content are by Amanda Masi. Reproduction or reuse requires written permission.</span></div></footer><Modal detail={detail} close={() => setDetail(null)} />
  </main>;
}
